# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- API_testing
schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - API_testing
  always: true

parameters:
- name: browser
  default: 'Chrome'
  values:
  - 'Firefox'
  - 'IE'
  - 'Chrome'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@3
  displayName: UI tests
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\**\*test.dll
      **\bin\**\*tests.dll
      **\bin\**\*TestProject1.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'Category!=API'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Screenshots'
  condition: failed()
  inputs:
      artifactName: '**\bin\**\Display*'
      targetPath: '$(System.DefaultWorkingDirectory)'
- task: VSTest@3
  displayName: API tests
  condition: succeededOrFailed()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\**\*test.dll
      **\bin\**\*tests.dll
      **\bin\**\*TestProject1.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'Category=API'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    publishRunAttachments: true


- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailureToPublishResults: true
    publishRunAttachments: true
